### ISSUE TITLE
Error when columns in request do not match columns in response from the API

### ISSUE THREAD

**Issue by mijnschoen** [pitchmuc/adobe_analytics_api_2.0#11]
I'm running into an error thrown by pandas: `ValueError: Length mismatch: Expected axis has 83 elements, new values have 88 elements` (see partial trace below)

I have the strong feeling this is due to the columns returned by the API might not always match the columns as set in the request sent to the API.
One reason why this might be the case, is when a metric is disabled. (I was able to reproduce the issue by adding two metrics in my request: one active and one **in**active).
Another reason might be when there is just no data for one of the columns. 

I see in your code the columns you set for the pandas dataframe are retreived from the request json, while it might be better to check this against the API response. 

Would that make sense?
```
...
c:\users\...\.virtualenvs\test-jupyter-aa-api-2ao00mzi\lib\site-packages\adobe_analytics_2\aanalytics2.py in _readData(data_rows, anomaly, cols, item_id)
    777     df = _pd.DataFrame(dict_data).T  # require to transform the data
    778     df.reset_index(inplace=True,)
--> 779     df.columns = cols
    780     return df
    781 

c:\users\...\.virtualenvs\test-jupyter-aa-api-2ao00mzi\lib\site-packages\pandas\core\generic.py in __setattr__(self, name, value)
   5285         try:
   5286             object.__getattribute__(self, name)
-> 5287             return object.__setattr__(self, name, value)
   5288         except AttributeError:
   5289             pass

pandas\_libs\properties.pyx in pandas._libs.properties.AxisProperty.__set__()

c:\users\...\.virtualenvs\test-jupyter-aa-api-2ao00mzi\lib\site-packages\pandas\core\generic.py in _set_axis(self, axis, labels)
    659 
    660     def _set_axis(self, axis, labels) -> None:
--> 661         self._data.set_axis(axis, labels)
    662         self._clear_item_cache()
    663 

c:\users\...\.virtualenvs\test-jupyter-aa-api-2ao00mzi\lib\site-packages\pandas\core\internals\managers.py in set_axis(self, axis, new_labels)
    176         if new_len != old_len:
    177             raise ValueError(
--> 178                 f"Length mismatch: Expected axis has {old_len} elements, new "
    179                 f"values have {new_len} elements"
    180             )

ValueError: Length mismatch: Expected axis has 83 elements, new values have 88 elements
```
As far as I

**Comment by Ryuno-Ki** [comment]
> I was able to reproduce the issue by adding two metrics in my request: one active and one active.

Is that a typo? I'd expected a „one active and one **in**active.

**Comment by mijnschoen** [comment]
Yes, a typo. (I've edited the comment).
I was debugging further and indeed found that the result of the API request includes a "columnErrors" attribute:

![image](https://user-images.githubusercontent.com/5900873/78654789-5ea54000-78c5-11ea-9259-037e3205ddec.png)

**Comment by Ryuno-Ki** [comment]
Cool, that you updated the OP.
I can't help you with your problem, though, since I left my company and thus have no access to an Adobe Analytics account any more.

@pitchmuc Please take over :-)

**Comment by mijnschoen** [comment]
I prepared a quick fix in a fork and will create a pull request in a moment.

**Comment by pitchmuc** [comment]
Hello guys
Thank you very much for giving the feedback and already suggested a solution.
I am totally in favor of checking from the response and not from the request, as some things can happen in between (apparently)
I'll review the code and let you know.
