### ISSUE TITLE
{‘error_code: ‘403025’, ‘message’: ‘Profile is not valid’}

### ISSUE THREAD

**Issue by yashjshah** [pitchmuc/adobe_analytics_api_2.0#13]
I keep getting this error for all the functions in the Analytics Class.

{‘error_code: ‘403025’, ‘message’: ‘Profile is not valid’}

I have the developer and admin rights for the Analytics Product.

Note: I am able to retrieve the JWT Authentication access token.

Please share how to resolve this

**Comment by pitchmuc** [comment]
Hello
It seems to me that you are not connecting the correct Product Profile to the API service in the console.adobe.io. Every time I heard this issue raising, it was a problem with the console.adobe.io setup. It may require some times as well. Check again now or on Monday. 
If not working, I would recommend to create a product profile attached to the API. 
In any case, it is not related to the python module, so I close this issue.
