### ISSUE TITLE
ValueError: If using all scalar values, you must pass an index

### ISSUE THREAD

**Issue by yashjshah** [pitchmuc/adobe_analytics_api_2.0#14]
I keep getting this error when creating a dataframe for the dimension function

ValueError: If using all scalar values, you must pass an index

Please share how to resolve this

**Comment by pitchmuc** [comment]
Normally the module (aanalytics2) already returns a Data Frame when calling for dimensions. 
Could you share example of what you are doing and the format of the data returned ?

**Comment by yashjshah** [comment]
![getdimensions_error_1](https://user-images.githubusercontent.com/35973711/84038034-fd512a00-a964-11ea-9d83-9d060d754f82.PNG)

Note: I am not using a class instance. I have write a function and calling it later in my case.

**Comment by pitchmuc** [comment]
Thanks. 
It seems that this is related to the the console.adobe.io setup. 
Are you sure you have assign the correct product profile to your API connection ? 

I tested in my hand it works : 
![image](https://user-images.githubusercontent.com/32903178/84068392-299e9200-a9c9-11ea-9fc9-1a1f2b0e0a66.png)

Also, make sure you use the latest version of the module
Current one is 0.0.6
You can verify by doing aanalytics2.__version__ 

You can upgrade by doing pip install aanalytics2 --upgrade.

**Comment by pitchmuc** [comment]
I will close this issue.
