### ISSUE TITLE
Invalid argument passed to getReport() in Line 846

### ISSUE THREAD

**Issue by Felipe-90** [pitchmuc/adobe_analytics_api_2.0#15]
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/480bc8a430c1c53a0018e670877c6596bc3f90bd/aanalytics2/aanalytics2.py#L846-L847

Hey.
First, thanks for your work!
I think that "headers" is an invalid argument passed to getReport() in Line 846-L847 of aanalytics2.py
or am I mistaken?

Best
Philipp

**Comment by pitchmuc** [comment]
Thanks Philipp,
You are correct I believe.
Have you encountered an error when trying to run the getReport method ? 
I will update the code, just trying to find out if it is urgent. 

Best,

**Comment by Felipe-90** [comment]
Hi.
Unfortunately, I have no access to Adobe JWT Authentication and had to change parts, s.t. the code works with OAuth. Then I encountered the bug. I fixed that in my code already. Thanks so much for the quick response and glad I could find a bug. :)
If I encounter anything else or have questions, I'll let you know. 
Best and keep up the good work. I'm learning a ton.
Philipp

**Comment by pitchmuc** [comment]
I am happy that you are learning for it. It proves that my code is not (too) ugly to be read. :) 
I ran the test. It seems to appears (mostly) when you try to run infinite report.
It seems that I forgot to call for the instance of that method itself as well. 
I'll let you know when I push the fix.

**Comment by pitchmuc** [comment]
I pushed the fix. Apparently my recent change broke several other stuffs.
let me know if it works now from the get go. 
Otherwise, I'll close the issue in a week.
