### ISSUE TITLE
KeyError: 'numberOfElements'

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#17]
It is an error I got for many weeks, now after debugging it (and not changing anything to the code), it worked again after failing the first time.
But now, 1 hour later, I tried again and I get this error again:

DEBUG:urllib3.connectionpool:https://analytics.adobe.io:443 "POST /api/compet2/reports HTTP/1.1" 504 0
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/pycharm-projects/dim28-repo/dim28etl/adobe/cost_check.py", line 176, in <module>
    run_script()
  File "D:/pycharm-projects/dim28-repo/dim28etl/adobe/cost_check.py", line 124, in run_script
    anom_cost_res = aa2.getReport(anom_cost_r, n_result='100')
  File "D:\pycharm-projects\dim28-repo\venv\lib\site-packages\adobe_analytics_2\aanalytics2.py", line 726, in getReport
    count_elements += report['numberOfElements']
KeyError: 'numberOfElements'

**Comment by pitchmuc** [comment]
Hello @loldenburg, 
You mean that you had this error, then it disappear and now it is back again ? 
Have you tried to upgrade to the latest version of the library ?
`pip install aanalytics2 --upgrade` 

Other questions : 
Are you able to run any other queries ? 
It seems that the response is not containing this information. 
However it is specified in the documentation : https://adobedocs.github.io/analytics-2.0-apis/#/reports/runReport 

I have 2 hypothesis : 
- for some reason (access) you cannot request report. 
- your report doesn't return any data or is misformed. 

Unfortunately, very hard to test without access. 

Let me know if you know a bit of python and we can try to debug it.

**Comment by loldenburg** [comment]
Yeah it is not the newest version. I wanted to try updating to the newest version, but then it breaks all of my code everywhere, seems like there was some change with the authentication. So I will first try to find a way to update that does not break everything. If you could help with that, appreciate it of course.

**Comment by pitchmuc** [comment]
Sure, I am happy to help on the task. I hope it is not urgent though as I am already quite busy. 
Which version do you have ? 
I haven't change a lot on the authentication for some time now. 

If you want to discuss this in private, you can use my email address : piccini [at] gmail [dot] com

**Comment by loldenburg** [comment]
was due to older version
