### ISSUE TITLE
KeyError: 'imsOrgs' when trying to get company ID fails sometimes (probably also needs "retry" functionality

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#24]
A script failed last night due to an error I sometimes get locally as well. 
I am trying
`cid = aa2.getCompanyId('0')`
But then this happens:
![image](https://user-images.githubusercontent.com/16238928/94417159-0407e500-0180-11eb-96ab-48c4b93d014a.png)

It is imho due to the same problem (instability of Adobe API which sometimes does not return anything, was escalated to Adobe). 
I will add a "retry" solution as well (like https://github.com/pitchmuc/adobe_analytics_api_2.0/issues/21 ) for my stuff, but maybe the aanalytics library should support this "natively".

That being said, this is harder as we don't even get an empty dataframe, we get an error that needs to be caught somehow.

**Comment by pitchmuc** [comment]
Thanks @loldenburg, I am considering now how to add this functionality. 
I am wondering if I add it on the creation of the instance. 
So you are doing this at some point : 
myLoginCompany = aa2.Analytics('cid',retry=3)

That would automatically add "3 retries" to each request if it fails.

**Comment by loldenburg** [comment]
Exactly. Ideally all the functions have a number of retries built-in which you can override with a retry parameter.

**Comment by pitchmuc** [comment]
I close this one as it is taking into account with the issue #21
