### ISSUE TITLE
Issue importing config file and generating Login class

### ISSUE THREAD

**Issue by pitchmuc** [pitchmuc/adobe_analytics_api_2.0#26]
When importing the config file and trying to generate the token via legacy or old method, the python interpreter is returning the following error.
```
Traceback (most recent call last):
File "C:\xxx\helpers.py", line 202, in
cid = aa2.getCompanyId(param)
File "C:\xxx\venv\lib\site-packages\aanalytics2\aanalytics2.py", line 136, in checking
config.config_object["token"] = retrieveToken(*args, **kwargs)
File "C:\xxx\venv\lib\site-packages\aanalytics2\aanalytics2.py", line 88, in retrieveToken
with open(private_key_path, 'r') as f:
PermissionError: [Errno 13] Permission denied: '.
```

**Comment by pitchmuc** [comment]
@loldenburg I wasn't able to reproduce the issue, I tried with the following path in my config file:

- private.key
- /private.key
- ./private.key
- sufolder/private.key

Everything works on my end. 
Could you share your path after importing the configuration file ? 

You can access it by doing the following : 
```python
import aanalytics2 as api2
api2.importConfigFile('myConfigfile.json")
api2.config.config_object['pathToKey']
```

**Comment by loldenburg** [comment]
It takes a lot of time to debug this because I first need to reinstall your newest library again, but the problem I think is not the path itself, but the logic in the config object.

**Comment by loldenburg** [comment]
send sth to your private mail as I dont want to share private paths here

**Comment by pitchmuc** [comment]
Normally this issue has been fixed with the latest releases.
