### ISSUE TITLE
Rename "deleteCalculatedMetrics" to "deleteCalculatedMetric" (singular) as it is only deleting one metric

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#27]
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/4f4213d228796cfd883f3b21182a3c1d9a55ba14/aanalytics2/aanalytics2.py#L945

def deleteCalculatedMetrics(self, calcID: str = None) -> object:

=> the calcID is a string, so it deletes one metric per execution only. That is why the function name with "Metric**s**" is misleading.

It would also be more consistent to the other calcMetrics function updateCalculatedMetric which also just updates one metric and not multiple ones.

**Comment by pitchmuc** [comment]
this has been solved with release 0.1.3
