### ISSUE TITLE
Request for component-metadata and Tag API methods

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#29]
Getting and writing tags to single or multiple components at once would be something really useful for my use cases. @pitchmuc Do you think this can be added easily? Or is it rather something for the long future?
https://adobedocs.github.io/analytics-2.0-apis/?urls.primaryName=Reporting%20APIs#/component-metadata%20-%20tags/findAllForCompany

**Comment by pitchmuc** [comment]
I will try to do the next official release on pypi with the solution from Yurii and the additional endpoints mentioned here.

**Comment by pitchmuc** [comment]
The latest git commit should include the Tags endpoint. 
Working through it, I have found that you cannot really create a Tag, you can assign it to components and component ids. 
So seems that API is to manage the Tags but not creating them. 
Let me know if you can check your use-cases before publishing on pypi. 
I have tested the GET methods and works for me.

**Comment by pitchmuc** [comment]
Done with the release of 0.1.3
