### ISSUE TITLE
AttributeError: module 'aanalytics2.config' has no attribute 'get'

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#35]
Sorry to steal more free time from you, but I tried to update today to the newest version (from git+https://github.com/xsavikx/adobe_analytics_api_2.0.git@4fc0e0cf11f3b93c3dae9b8d9f90b0fa6163375c#egg=aanalytics2
, which made the version from early Nov work for me), but now I get this error:

![image](https://user-images.githubusercontent.com/16238928/102700677-d9de3480-424f-11eb-9928-928475a16d72.png)

This is the code (aa2 is my api2 object):
```
cfg.aaconfig_bycomp(company)
cid = aa2.getCompanyId('0')
```

cfg.aaconfig_bycomp(company) does this:

```
def function_that_is_called_by_cfg.aaconfig_bycomp(company):
    aa2.config.org_id = 'xxx@AdobeOrg'
    aa2.config.tech_id = 'xxx@techacct.adobe.com'
    aa2.config.api_key = 'xxx'
    aa2.config.header["X-Api-Key"] = aa2.config.api_key
    aa2.config.secret = 'xxx'
    aa2.config.pathToKey = AA_PRIVATE_KEY_PATH_COMP
    aa2.configure(org_id=aa2.config.org_id, tech_id=aa2.config.tech_id, secret=aa2.config.secret,
                  path_to_key=aa2.config.pathToKey, client_id=aa2.config.api_key)
    return aa2

Thanks for help with this.

**Comment by loldenburg** [comment]
This works btw:
 ```
    cfg.aaconfig_bycomp(company)
    login = aa2.Login()
    cid = login.getCompanyId()[0]['globalCompanyId']
    ags = aa2.Analytics(cid)
```
But using this method would mean I would have to update code in a looot of files and then QA all these scripts. Work for a whole day. According to docs, the aa2.getCompanyId() method should work

**Comment by pitchmuc** [comment]
Hello @loldenburg 
You are right that it should still work. 

Sorry I missed that. I tried to integrate tests to make my releases more stable but the legacy version is not included :( 
Good news is that I was able to reiterate that issue and fix it. 
The version 0.1.8 is now live, can you test it ?  

Old version: 
![image](https://user-images.githubusercontent.com/32903178/102707975-d70b3000-429f-11eb-9291-a483875635e2.png)

New version:
![image](https://user-images.githubusercontent.com/32903178/102707981-e4281f00-429f-11eb-839a-942585f373c7.png)

**Comment by pitchmuc** [comment]
What the previous version you used ?  

I would have expected your config method to be something like this: 

```python
def function_that_is_called_by_cfg.aaconfig_bycomp(company):
    aa2.config.config_object["org_id"]= 'xxx@AdobeOrg'
    aa2.config.config_object["tech_id"] = 'xxx@techacct.adobe.com'
    aa2.config.config_object["api_key"]= 'xxx'
    aa2.config.header["X-Api-Key"] = aa2.config.api_key
    aa2.config.config_object["secret"] = 'xxx'
    aa2.config.config_object["pathToKey"] = AA_PRIVATE_KEY_PATH_COMP
    aa2.configure(org_id=aa2.config.config_object["org_id"], tech_id=aa2.config.config_object["tech_id"], secret=aa2.config.config_object["secret"],path_to_key=aa2.config.config_object["pathToKey"], client_id=aa2.config.config_object["api_key"])
    return aa2
```

also `aa2.config.config_object["api_key"]` is now `aa2.config.config_object["client_id"]` but it would work with "api_key" as well for you as you are pushing it to a dictionary and re-using it anyway with the correct parameter (`client_id`). 
This one is not from me but Adobe changed the name of it over the year.

**Comment by loldenburg** [comment]
What the previous version you used ?

I used the fork mentioned above (sorry link for browser is https://github.com/xSAVIKx/adobe_analytics_api_2.0/commit/4fc0e0cf11f3b93c3dae9b8d9f90b0fa6163375c ). That was necessary back then to make an update of the API2 Wrapper work.

Will try the new version, thanks!

**Comment by loldenburg** [comment]
works locally, also the other config syntax works now. Now the always tricky test in the cloud... ;)

**Comment by pitchmuc** [comment]
encouraging !

**Comment by loldenburg** [comment]
Works in the cloud, too. I also now took the time to encapsulate the whole config, getCid and login stuff so if it changes in the future, I have to change only function. So feel free to remove the old getCompanyID() method (unless others need it).

Really cool to finally use the Projects API!!!

THANK YOU, JULIEN, and have a nice Christmas! :)

**Comment by pitchmuc** [comment]
You are the only one to use it that I know. 
It will gradually be discarded in the documentation and will be removed in the future. 

Have a nice christmas as well and guten Rutsch ;)
