### ISSUE TITLE
getVirtualReportSuites() should not create a CSV file by default

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#36]
I cannot run getVirtualReportSuites() on a server without write permissions because the function always by default creates a CSV file. This should not be the default behaviour.

The docstring is also misleading:

            save : OPTIONAL : if set to True, it will save the list in a file. (Default False)

**Comment by pitchmuc** [comment]
can you try forcing the `save=False` state ? 
I will update it

**Comment by pitchmuc** [comment]
Fix in the repo. We'll come next week in a release (probably 0.1.9)
This was so stupid that I need time to digest this mistake.

**Comment by loldenburg** [comment]
I didn't need the function really until now, so it is probably not the most important function, Thanks for fixing! 👍

**Comment by pitchmuc** [comment]
fix in release 0.1.9
