### ISSUE TITLE
Consider changing the license

### ISSUE THREAD

**Issue by xSAVIKx** [pitchmuc/adobe_analytics_api_2.0#38]
The current GNU license is a strong no-go for most users that would like to ever build a non-open-sourced solution.

While it may look like a proper thing to do to use this license, it usually prevents bigger players from using the library because as per the license everyone is obliged to use the same license and to disclose their source code.

I'd really recommend moving towards smth like [Apache 2](https://www.apache.org/licenses/LICENSE-2.0) or [MIT](https://opensource.org/licenses/MIT) license if there are no personal reasons for having the current one.

**Comment by pitchmuc** [comment]
Thanks for the proposal. I need to look more into this. 
My main motivation is that people should provide feedback / PR to the main source code so everyone can gain from other experiences. 

I don't mind that people re-sell it or productionize it but I don't want people fixing all issues (main) on their own and never give back these fixes to the community.

We are providing lots of value for companies for free and if they decide to invest further in this module (by using it to production), it should  be at least provide value for us (analytics community).

If one of your 2 proposed license is providing flexibility and also ensure participation in the code improvement. 
I'll definitely consider it.

**Comment by xSAVIKx** [comment]
Unfortunately, any licensing will not defend the open-source here. There'd always be companies who'd use the software and never give anything back. But this particular license can (I'd say will) lead to people not even trying to work with the module.

E.g. the company I help with some backends has a strict licensing policy and no GNU-licensed library can be ever used. It's OK to use the tooling, but not a library.

**Comment by pitchmuc** [comment]
I understand that it may be a bit too much as you need to publish the source-code. 
That is what I found the closest to actually getting anything back from people/companies working on it. 
I will consider it over the next days (and most probably change it) just need to find the one being the best suited between the 2 choices.
I'll run some research with wikipedia ;) 
Have a nice holidays season if you are off.

**Comment by Ryuno-Ki** [comment]
Perhaps GitHub's Choose A License might help you:

* [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/)
* [GPL v3 License](https://choosealicense.com/licenses/gpl-3.0/)
* [MIT License](https://choosealicense.com/licenses/mit/)

**Comment by pitchmuc** [comment]
After reading the licenses proposed by GitHub and lots of consideration, I believe that Apache License 2 seems the right choice.
 
I hope that the change from the license material being documented will enable us to keep a good state for this library even if a company create a personal version of this module (still counting on good will though).

From my understanding, the MIT license is a bit too permissive as the users will not know what comes from the original module and what is coming from their developed branche.

It brought me lots of "existential" questions about the project itself and what I wanted to achieve with it. Thanks for it @xSAVIKx.

The goal here is to **try to** avoid that the project stops being a "community-enhanced" project but still allow private entities to have their own (private) version when needed, stating clearly what has been developed where/by whom.
I do not wish to be a blocker to use what has been developed by the community but I have been a bit too much disappointed by corporate behavior to offer a MIT license (yet).

On this day, I will push the change today for aanalytics2 and probably aepp library so we can start 2021 fresh and clean.

Taking the opportunity to wish a happy new year.

**Comment by pitchmuc** [comment]
Published live via commit 2f6a4b3f57b7606f0aa3acf96dacae87246f1624
