### ISSUE TITLE
Update PyJWT dependency

### ISSUE THREAD

**Issue by omgMath** [pitchmuc/adobe_analytics_api_2.0#39]
PyJWT 2.0.0 was released some days ago (see https://github.com/jpadilla/pyjwt/releases/tag/2.0.0)
It would be nice if we could update to the newest release.

**Comment by pitchmuc** [comment]
Hello
Have you checked that this is backward compatible ? 
It seems to drop support for PyCrypto, that it used and requires a new script. 

I understand the request and I will tackle it, so it is using the latest version. 
Because it is such an important element of the whole module (and I just got a child) it may take a while before it is updated. 

Best,

**Comment by omgMath** [comment]
>  Have you checked that this is backward compatible ?
It is not. There is a change titled "Return tokens as string not bytes", so this will imply some changes for this library.

>  Because it is such an important element of the whole module (and I just got a child) it may take a while before it is updated.
Thank you! And congratulations!

**Comment by pitchmuc** [comment]
Hello
I was able to work on it today and I developed a new branch that I would like you to test before releasing it. 
It seems that the encoded JWT returned by the pyJWT 2.0.0 module is not the same (than previous versions) and doesn't support the decode method I have in my current implementation.
Hence, you may had issues. 

I hope that this branch will fix the issue. It does in my virtual env but I would like external test as this is critical for the stability of the module.

It is backward compatible.
However, I will not provide support for the `retrieveToken` method not located in the `Login` class.

You can find the branch with this head : 2e6be28

**Comment by pitchmuc** [comment]
Thanks for your help on this.
Upgraded with the following commit 832ada2

I will close when release is done on pypi (v 0.2.0)

**Comment by pitchmuc** [comment]
resolve with release of version 0.2.0
