### ISSUE TITLE
Name functions in snake_case

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/adobe_analytics_api_2.0#4]
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/04e29001025a6440e972efe6b1b9f292aac956a8/adobe_analytics_2/aanalytics2.py#L45

[PEP8 recommends snake_case](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) instead of camelCase.

**Comment by pitchmuc** [comment]
Thanks Andre ! 
I am refactoring this API to make it available on the pypi repository. I will definitely update that.
