### ISSUE TITLE
ConfigFile

### ISSUE THREAD

**Issue by akashachanta01** [pitchmuc/adobe_analytics_api_2.0#45]
I recently installed your aanalytics2 package . However to get started the config file in you package requires me to fill in org id , api key, tech id, secret and pathtokey. But my org has asked me to use the swagger to get key api key , org id and bearer token to access apis. So, how do I work with your package if I only have org id, api key, bearer token ?

**Comment by pitchmuc** [comment]
thanks for logging that issue @akashachanta01 
It should be possible to connect with only the following information: 
- org id
- client ID / api key
- token

but we would need to trick the system a bit. 
I will provide a function to do that if this succeed. 

You would need to use the configure method to add the org_id and "fake" other info. 
So your python code should look something like this

```python
import aanalytics2
my_org_id = "realOrgID"
my_client_id = "realClientId"
aanalytics2.configure(org_id=my_org_id,tech_id="anyString", secret="anyString",path_to_key="anyString",client_id=my_client_id)
```
once you have setup that, you will need to set manually the token and an expiration date for the token.
So I would do something like this afterwards:

```python
myToken = "realToken"
import time
expiration = int(time.time()) + 20 * 60 * 60
aanalytics2.config.config_object['date_limit'] = expiration
aanalytics2.config.config_object['token'] = myToken
aanalytics2.config.header['Authorization'] = 'Bearer '+token
```

Once that is done, you should be able to use the module like in the videos or documentation. 
Note : You won't have automatic refreshing of the token after 20 hours in this case.

**Comment by akashachanta01** [comment]
Thanks @pitchmuc , this worked out fine for me . Will reach if I have any other questions . Thanks !

**Comment by pitchmuc** [comment]
I have streamlined this method so you can use the `configure` method in order to pass the information. 
Please refer to this part of the [get-started documentation](https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/master/docs/getting_started.md#alternative-2--using-oauth-token)
