### ISSUE TITLE
Config File - unable to find private key under path

### ISSUE THREAD

**Issue by courtney-aiello** [pitchmuc/adobe_analytics_api_2.0#46]
Hi, 
Once I create and import the config file, and try 
`cid = api2.getCompanyId()`
`cid`

I get the following error:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-33fb48ecb4da> in <module>
----> 1 cid = api2.getCompanyId()
      2 cid

/opt/anaconda3/lib/python3.8/site-packages/aanalytics2/aanalytics2.py in checking(*args, **kwargs)
     27         now = time.time()
     28         if now > config.config_object["date_limit"] - 1000:
---> 29             token_with_expiry = token_provider.get_token_and_expiry_for_config(config.config_object, *args,
     30                                                                                **kwargs)
     31             token = token_with_expiry['token']

/opt/anaconda3/lib/python3.8/site-packages/aanalytics2/token_provider.py in get_token_and_expiry_for_config(config, verbose, save, *args, **kwargs)
     17         save : OPTIONAL : Default False. If set to True, save the toke in the .
     18     """
---> 19     private_key = configs.get_private_key_from_config(config)
     20     header_jwt = {
     21         'cache-control': 'no-cache',

/opt/anaconda3/lib/python3.8/site-packages/aanalytics2/configs.py in get_private_key_from_config(config)
    137     private_key_path = find_path(config['pathToKey'])
    138     if private_key_path is None:
--> 139         raise FileNotFoundError(f'Unable to find the private key under path `{config["pathToKey"]}`.')
    140     with open(Path(private_key_path), 'r') as f:
    141         private_key = f.read()

FileNotFoundError: Unable to find the private key under path `<path/to/your/privatekey.key>`.

I tried moving the key to a new path, but I am still encountering the error message above. 

Thank you

**Comment by pitchmuc** [comment]
Hello @courtney-aiello 
Have you imported the config file (`importConfigFile`) or used the `configure` method ? 

If not, you probably have the answer of your problem in the [documentation](https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/master/docs/getting_started.md)

**Comment by courtney-aiello** [comment]
my config.json had a missing curly brace. I feel utterly silly. Thank you for taking the time to respond.

**Comment by pitchmuc** [comment]
No worry. 
Happy to see that it works for you as well now.
