### ISSUE TITLE
Why globals?

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/adobe_analytics_api_2.0#5]
Hi @pitchmuc,

what is your motivation for using globals in this code part?
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/04e29001025a6440e972efe6b1b9f292aac956a8/adobe_analytics_2/aanalytics2.py#L49-L54

**Comment by pitchmuc** [comment]
I want to make sure that the new value I will retrieve will not be scoped by my function. 
To ensure that, I set the dimensions as global. 
You don't think it is necessary ?

**Comment by pitchmuc** [comment]
I am closing this comment because I changed the architecture of the API to use classes. 
In classes the scope of the variable are much clearer to interpret. 

Thanks for your feedback !
