### ISSUE TITLE
API request handling sometimes does not work

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#51]
I still do get issues with 429 being returned (too many requests) sometimes when I run many requests in a row. E.g. here a client wanted to delete 1000 Workspaces via the [Adobe Component Manager for Google Sheets](https://lukas-oldenburg.medium.com/google-sheets-bulk-component-editor-for-adobe-analytics-video-ddf726ec2ac), so I am firing a loop to delete project by project:

![image](https://user-images.githubusercontent.com/16238928/112320618-77159280-8caf-11eb-8fee-71b851e3d54d.png)
From the logs, I see that at least one of the requests had this problem:
![image](https://user-images.githubusercontent.com/16238928/112320975-cfe52b00-8caf-11eb-986f-b3e21f1792f2.png)

**Comment by pitchmuc** [comment]
Got it. 
I have my handling of 429 only on the GET requests, not in the delete.
It would make sense to have that there as well. 
I'll add them.

**Comment by pitchmuc** [comment]
Enhancement part of the 31fd34f commit.
