### ISSUE TITLE
some getProject requests throw error "segmentGroups"

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#52]
![image](https://user-images.githubusercontent.com/16238928/112335559-a1ba1800-8cbc-11eb-8793-58417263adff.png)

WARNING:root:Could not get details for project ID: 5877a42abdf14b9445bb811c, error: 'segmentGroups'

The project is older, but I didn't have this issue before. I updated to newest version 0.2.5 from 0.2.4 yesterday. I will try to gather more details.

When I switch on Verbose, it says:
request URL : https://analytics.adobe.io/api/XXX/projects/5877a42abdf14b9445bb811c?expansion=definition%2CownerFullName%2Cmodified%2Cfavorite%2Capproved%2Ctags%2Cshares%2CsharesFullName%2CreportSuiteName%2CcompanyTemplate%2CaccessLevel
statut_code : 200
Then: {KeyError}'segmentGroups'

**Comment by loldenburg** [comment]
I opened the project from the AA interface and saved it again. Now it worked. But there seems to be some issue with older projects.

**Comment by loldenburg** [comment]
The problem is the new way that the response of the getProject request is forced into -> Union[dict,Project]
Here it tries to get a "segmentGroups" property which does not exist in all projects:
```
        for panel in workspace['panels']:
            if "reportSuite" in panel.keys():
                dict_elements['reportSuites'].append(panel['reportSuite']['id'])
            elif "rsid" in panel.keys():
                dict_elements['reportSuites'].append(panel['rsid'])
            **filters: list = panel['segmentGroups']**
            if len(filters) > 0:
```
This also explains why it did not cause issues before, only after updating the aa2 library yesterday.

**Comment by loldenburg** [comment]
maybe improve this way:
```
if panel.get('segmentGroups') is not None:
   for element in filters:
```

**Comment by loldenburg** [comment]
I will send you an example response of such projects via email. As I said, I would want an option that prevents forcing the response into the Project dictionary.

**Comment by loldenburg** [comment]
Boy sorry for the many messages, but I think you already had this option in mind with the projectClass parameter, however:

```
if projectClass:
 if verbose:
 print('building an instance of Project class')
 myProject = Project(res)
 return myProject
self.projectsDetails[projectId] = Project(res) !!! Response is forced into "Project" even when projectClass is False
```

**Comment by pitchmuc** [comment]
Thanks a lot @loldenburg for the debug.

For the last message, I am trying to be smart (It doesn't suit me well apparently).
The idea is to cache the Project detail in an attribute (dictionary) so you can easily access them later on again if you need to.
So you don't need to do an API call again (as it is expensive in time and in API call budget - limit of 12 for 6s)

I replace it with a try: 
```
try:
    self.projectsDetails[projectId] = Project(res)
except:
    if verbose:
      print('WARNING : Cannot convert Project to Project class')
```

For the original fail, I will fix it by returning an empty list: 
```
filters: list = panel.get('segmentGroups',[])
```
As I am doing a `if len(filters) > 0:`  later on.

True, it is tough to expect anything from undocumented (unsupported?) API. 
I still see lots of benefits from it though :)

**Comment by pitchmuc** [comment]
I hope to make the changes tonight for an update in Git tomorrow.
Probably be a Patch (something like "0.2.6-1")

**Comment by loldenburg** [comment]
Yeah it totally makes sense to cache the object in a certain standard data model, I was not disputing that, I just wondered why you forced this, relying on a certain model that may change soon as it is as you say unsupported and undocumented. 
I hugely appreciate it anyway and I am aware of the potential problems that come with it. THANKS!

My scripts don't need to cache the project definition however and memory is always a potential issue, so being able to skip this row "self.projectsDetails[projectId] = Project(res)" entirely with a flag (e.g. cache=False) would be even a bit more performance and memory-saving.

**Comment by pitchmuc** [comment]
Sound argument. I'll add that option !

**Comment by pitchmuc** [comment]
Enhancement part of the 31fd34f commit.
fyi : I messed up the version number, the new version is `0.2.6` not the `0.2.6-1`
You may have hard time installing it if you try a pip upgrade and you currently have the `0.2.6-1`. 
Nothing change except that part and some release info. 
So you can stay with the `0.2.6-1`
