### ISSUE TITLE
Stick to one quotation style

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/adobe_analytics_api_2.0#7]
Normally, you are using single quotes for your dictionaries.
Why do you switch to double ones in https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/04e29001025a6440e972efe6b1b9f292aac956a8/adobe_analytics_2/aanalytics2.py#L81-L85 and following?

**Comment by pitchmuc** [comment]
Honest response : probably because I coded it on a different day with less python and more JS (where I am more used to use double quotation there). 
That is a good point for consistency.

**Comment by Ryuno-Ki** [comment]
I know what you mean :-D

But a linter can be your friend here ;-)
Or let black do the boring stuff for you.

**Comment by pitchmuc** [comment]
Yes. I feel the important tip there. 
I definitely need to do some black magic before releasing my stuff. 
I started to work on my new project with someone else and he is a black user... it takes time to get used to tat formatting. 
Let's say it is for the greater good :)

**Comment by pitchmuc** [comment]
I finally used black to format my file. :) 
I will close that one.
