### ISSUE TITLE
Avoid Pokémon exception handling

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/adobe_analytics_api_2.0#8]
Please try to avoid [Pokémon exception handling](https://www.dodgycoder.net/2011/11/yoda-conditions-pokemon-exception.html) in 
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/04e29001025a6440e972efe6b1b9f292aac956a8/adobe_analytics_2/aanalytics2.py#L139

If I [read the docs](https://requests.kennethreitz.org/en/master/user/quickstart/#json-response-content) right, you should handle a `ValueError` instead.

**Comment by pitchmuc** [comment]
Again good point! 
I changed it and it will be part of the next release. 
Thanks again. 
All of these comments are super useful for me to improve !
